apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldmonitor.componentFullname" (list . "redis") }}
  labels:
    {{- include "worldmonitor.componentLabels" (list . "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "worldmonitor.componentSelectorLabels" (list . "redis") | nindent 4 }}
