apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldmonitor.componentFullname" (list . "app") }}
  labels:
    {{- include "worldmonitor.componentLabels" (list . "app") | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "worldmonitor.componentSelectorLabels" (list . "app") | nindent 4 }}
