apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldmonitor.componentFullname" (list . "redis-rest") }}
  labels:
    {{- include "worldmonitor.componentLabels" (list . "redis-rest") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redisRest.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "worldmonitor.componentSelectorLabels" (list . "redis-rest") | nindent 4 }}
